# Generated by Django 5.2.4 on 2025-07-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geojson_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AtmosphericData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('pressure', models.FloatField()),
                ('source', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='pollution_a_timesta_708da7_idx'), models.Index(fields=['latitude', 'longitude'], name='pollution_a_latitud_0f418e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroundMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('station_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pm2_5', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='pollution_a_timesta_60e39b_idx'), models.Index(fields=['station_id'], name='pollution_a_station_65ca56_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictedPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pm2_5_predicted', models.FloatField()),
                ('pm10_predicted', models.FloatField()),
                ('confidence_score', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='pollution_a_timesta_866a19_idx'), models.Index(fields=['latitude', 'longitude'], name='pollution_a_latitud_13f089_idx')],
            },
        ),
        migrations.CreateModel(
            name='SatelliteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('aod_value', models.FloatField()),
                ('satellite_source', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='pollution_a_timesta_9f7613_idx'), models.Index(fields=['latitude', 'longitude'], name='pollution_a_latitud_9519fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geojson_data', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollution_app.state')),
            ],
        ),
    ]
